import { HelperTopic } from './types';

export const helperTopics: HelperTopic[] = [
  {
    id: 'crying',
    title: 'Baby is crying',
    icon: 'water-outline',
    description: 'Work through these steps to comfort your baby',
    steps: [
      'Check if baby is hungry - offer a feed (look for rooting, lip smacking)',
      'Check the diaper - change if wet or dirty',
      'Check temperature - feel the back of their neck (should be warm, not hot or cold)',
      'Try swaddling snugly with arms in',
      'Hold baby on their side or stomach against your body',
      'Make a loud "shhhh" sound near their ear',
      'Gently rock or sway baby',
      'Offer a pacifier for comfort sucking',
      'Try skin-to-skin contact on your bare chest',
      'Go for a walk or drive - motion often calms babies',
      'If nothing works after 20+ minutes, it\'s okay to put baby in a safe place and take a short break',
    ],
  },
  {
    id: 'wont-sleep',
    title: 'Baby won\'t sleep',
    icon: 'moon-outline',
    description: 'Help your baby settle down for sleep',
    steps: [
      'Check wake window - newborns can only handle 45-90 min awake',
      'Dim the lights and reduce noise',
      'Start a calming routine: diaper change, swaddle, feed',
      'Rock baby gently while making "shhhh" sounds',
      'Try white noise (fan, app, or shushing)',
      'Make sure the room isn\'t too warm or too cold (68-72F / 20-22C is ideal)',
      'Hold baby until drowsy, then place in crib on their back',
      'If baby fusses in crib, wait 1-2 minutes before picking up',
      'Try a pacifier - sucking is soothing',
      'Sometimes a car ride or stroller walk does the trick',
      'Remember: this is temporary. Sleep patterns improve with time',
    ],
  },
  {
    id: 'fussy',
    title: 'Baby is fussy',
    icon: 'alert-circle-outline',
    description: 'When baby seems uncomfortable but you can\'t figure out why',
    steps: [
      'Rule out the basics: fed, clean diaper, comfortable temperature',
      'Try the 5 S\'s: Swaddle, Side position, Shush, Swing, Suck',
      'Check for gas - try bicycle legs or gentle tummy massage',
      'Look for hair tourniquets (hair wrapped around fingers or toes)',
      'Check that clothing isn\'t too tight or scratchy',
      'Try a different holding position - some babies like facing outward',
      'Run a warm bath if baby usually enjoys it',
      'Step outside for fresh air - change of scenery helps',
      'Put on some music or hum a familiar tune',
      'Tag in your partner if you\'re getting frustrated - it\'s okay to take turns',
    ],
  },
  {
    id: 'not-eating',
    title: 'Baby hasn\'t eaten in a while',
    icon: 'restaurant-outline',
    description: 'When it\'s been longer than usual since the last feed',
    steps: [
      'Check the last feed time in the app dashboard',
      'Newborns should eat every 2-3 hours (8-12 times per day)',
      'Try skin-to-skin contact to stimulate hunger',
      'Gently wake baby if sleeping past feeding time: undress slightly, tickle feet',
      'Try different feeding positions',
      'If bottle feeding, check milk temperature (should feel warm on your wrist)',
      'Watch for hunger cues: rooting, hand-to-mouth, lip smacking',
      'If baby consistently refuses feeds or seems lethargic, call your pediatrician',
      'Track the number of wet diapers - fewer than 6 per day may signal insufficient feeding',
      'Stay calm - occasional longer stretches between feeds are usually okay for older newborns',
    ],
  },
  {
    id: 'uncomfortable',
    title: 'Baby seems uncomfortable',
    icon: 'body-outline',
    description: 'When baby is squirming, arching, or seems in discomfort',
    steps: [
      'Check for wet or dirty diaper',
      'Look for signs of gas: pulling legs up, arching back, red face',
      'Try bicycle legs: gently cycle baby\'s legs while they lie on their back',
      'Massage tummy in gentle clockwise circles',
      'Hold baby face-down along your forearm (football hold) for gas relief',
      'Burp baby thoroughly - try over shoulder, sitting up, or face-down on lap',
      'Check for diaper rash - apply barrier cream if needed',
      'Make sure clothing and swaddle aren\'t too tight',
      'Check room temperature and adjust layers',
      'If baby seems in pain or discomfort persists, contact your pediatrician',
    ],
  },
];
